version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stock-db
    environment:
      POSTGRES_DB: stockanalyzer
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/main/resources/data/sectors-industries.sql:/docker-entrypoint-initdb.d/01-seed.sql
    restart: unless-stopped

  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/stockanalyzer
      DB_USERNAME: stockuser
      DB_PASSWORD: stockpass
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped

volumes:
  pgdata:
