version: '3.8'

services:
  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-api
    ports:
      - "9090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_URL: jdbc:postgresql://172.17.0.1:5433/stockanalyzer?sslmode=disable
      DB_USERNAME: tiger
      DB_PASSWORD: Freewalk345^
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped
